name: Vanilla-javascript-typesystem build and Release

on:  
  push:
    brain:
      - main

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Run release script
        run: ./.github/scripts/release.sh
        shell: bash